name: Test Pipeline

on:
  push:
    paths:
        - 'front/**'
    branches:
      - master
  pull_request:
    paths:
        - 'front/**'
    types: [opened, synchronize, edited]
    branches:
      - master
jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Go to correct directory
        run: cd front/
      
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn install
      - name: Linting
        run: yarn lint
      - name: Static type checking
        run: yarn tsc
